dependencies:
  build:
    - ruby:2.6.2

build_targets:
  - name: default
    container: 
      image: yourbase/yb_ubuntu:18.04
    commands:
        - apt-get install -y libmysqlclient-dev
        - bundle install --jobs=3 --retry=3
        - bundle exec rake
        
ci:
  builds:
    - name: default
      build_target: default
