dependencies:
  build:
    - ruby:2.6.2

build_targets:
  - name: default
    container: 
      image: yourbase/yb_ubuntu:18.04
    commands:
        - chmod +x yourbased.sh
        - ./yourbased.sh
    environment:
        - SOLIDUS_BRANCH=v2.8
        - DB=postgres
ci:
  builds:
    - name: default
      build_target: default
